// react-src/components/form-field/form-field.js
import React, { Component } from "react";
require('./form-field.css');

import TextField from '../text-field/text-field';
import SelectField from '../select-field/select-field';

export default class FormField extends Component {
  onChangeHandler = value => {
    if (!this.props.onChange) return;

    this.props.onChange(value, event);
  }
  
  render() {
    return (
      <div
        className={`form-field${this.props.type === 'checkbox' ? ' form-field_type_checkbox' : ''}`}
      >
        <label htmlFor={this.props.id} className="form-field__label">
          {this.props.label}
        </label>

        {this.props.type === 'select' && (
          <SelectField
            mix="form-field__control"
            options={this.props.options}
            id={this.props.id}
            name={name}
            onChange={this.onChangeHandler}
            value={this.props.value}
          />
        )}
        {this.props.type === 'checkbox' && (
          <input
            className="form-field__control"
            type="checkbox"
            id={this.props.id}
            name={this.props.name}
            onChange={e => this.onChangeHandler(e.target.checked)}
            checked={this.props.value}
          />
        )}
        {this.props.type !== 'checkbox' && this.props.type !== 'select' && (
          <TextField
            mix="form-field__control"
            type={this.props.type}
            id={this.props.id}
            name={this.props.name}
            onChange={this.onChangeHandler}
            value={this.props.value}
          />
        )}
      </div>
    );
  }
}

// src/components/form-field/form-field.svelte
<script>
  import TextField from '../text-field/text-field';
  import SelectField from '../select-field/select-field';

  export let id = '';
  export let name = '';
  export let label = '';
  export let type;
  export let options;
  export let value;
  export let checked;
  export let onChange;

  const isCheckbox = type === 'checkbox';
  
  function onChangeHandler(event) {
    onChange(isCheckbox ? event.target.checked : event.target.value, event);
  }
</script>

<div
  class="form-field"
  class:form-field_type_checkbox={isCheckbox}
>
  <label for={id} class="form-field__label">
    {label}
  </label>

  {#if type === 'select'}
    <SelectField
      mix="form-field__control"
      {options}
      {value}
      {id}
      {name}
      onChange={onChangeHandler}
    />
  {:else if isCheckbox}
    <input
      class="form-field__control"
      type="checkbox"
      {checked}
      {id}
      {name}
      on:change={onChangeHandler}
    />
  {:else}
    <TextField
      mix="form-field__control"
      {type}
      {value}
      {id}
      {name}
      onChange={onChangeHandler}
    />
  {/if}
</div>

<style>
  .form-field__label {
    display: block;
    color: #333;
    font-size: 14px;
    margin-bottom: 5px;
  }

  .form-field_type_checkbox {
    display: flex;
  }

  .form-field_type_checkbox > .form-field__control {
    order: 1;
    margin-right: 5px;
  }

  .form-field_type_checkbox > .form-field__label {
    order: 2;
  }
</style>
