// src/components/footer/footer.svelte
<script>
  const year = new Date().getFullYear();
</script>

<footer class="footer">
  <div class="footer__copyright">Будильник на Svelte {year}</div>

  <div class="footer__about-link">
    <a href="/about">О сервисе</a>
  </div>
</footer>

<style>
  .footer {
    display: flex;
    justify-content: space-between;
    padding: 10px;
    border-top: 1px solid #ddd;
  }

  .footer__copyright {
    color: #999;
  }
</style>

// react-src/components/footer/footer.js
import React, { Component } from "react";
require('./footer.css');

export default class Footer extends Component {
  render() {
    return (
      <footer className={['footer', this.props.mix].join(' ')}>
        <div className="footer__copyright">Будильник на Svelte {new Date().getFullYear()}</div>

        <a className="footer__about-link" href="#/about">О сервисе</a>
      </footer>
    );
  }
}
