// src/components/select-field/select-field.svelte
<script>
  export let mix = '';
  export let id = '';
  export let name = '';
  export let options = [{ value: '', text: '' }];
  export let value;
  export let onChange;

  const params = {
    id,
    name,
  };
</script>

<select
  class={['select-field', mix].join(' ')}
  on:change={onChange}
  on:blur={onChange}
  bind:value={value}
  {...params}
>
  {#each options as option}
    <option value={option.value}>
      {option.text}
    </option>
  {/each}
</select>

<style>
  .select-field {
    width: 100%;
    height: 40px;
    box-sizing: border-box;
    line-height: 40px;
    padding: 0 5px;
    border: 1px solid #777;
    border-radius: 0;
    outline: none;
    height: 40px;
    line-height: 40px;
  }

  .text-field:focus {
    box-shadow: inset 0 0 10px -5px rgba(0,0,0,.5);
  }
</style>

// react-src/components/select-field/select-field.js
import React, { Component } from "react";
require('./select-field.css');

export default class SelectField extends Component {
  constructor(props) {
    super(props);

    this.state = {
      value: this.props.value || '',
    };
  }

  componentDidUpdate() {
    if (this.props.value !== this.state.value) {
      this.setState({
        value: this.props.value,
      });
    }
  }

  onChange = event => {
    this.setState({
      value: event.target.value,
    }, () => {
      this.props.onChange(this.state.value, event);
    });
  }

  render() {
    const params = {
      id: this.props.id,
      name: this.props.name,
    };

    return (
      <select
        className={['select-field', this.props.mix].join(' ')}
        onChange={this.onChange}
        value={this.state.value}
        {...params}
      >
        {this.props.options.map(option => {
          return (
            <option value={option.value} key={option.value}>
              {option.text}
            </option>
          );
        })}
      </select>
    );
  }
}
